//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abmEmpleados
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> IdTipoDto { get; set; }
        public Nullable<int> NumDocumento { get; set; }
        public string Estado { get; set; }
    
        public virtual tiposDocumentos tiposDocumentos { get; set; }
    }
}
