//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abmEmpleados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EpleadosEntities : DbContext
    {
        public EpleadosEntities()
            : base("name=EpleadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<tiposDocumentos> tiposDocumentos { get; set; }
    
        public virtual int SP_SaveEmpleado(string codigo, string apellido, string nombre, string fechaAlta, Nullable<int> tipoDto, Nullable<int> numDto)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var fechaAltaParameter = fechaAlta != null ?
                new ObjectParameter("FechaAlta", fechaAlta) :
                new ObjectParameter("FechaAlta", typeof(string));
    
            var tipoDtoParameter = tipoDto.HasValue ?
                new ObjectParameter("TipoDto", tipoDto) :
                new ObjectParameter("TipoDto", typeof(int));
    
            var numDtoParameter = numDto.HasValue ?
                new ObjectParameter("NumDto", numDto) :
                new ObjectParameter("NumDto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SaveEmpleado", codigoParameter, apellidoParameter, nombreParameter, fechaAltaParameter, tipoDtoParameter, numDtoParameter);
        }
    }
}
